Network Namespace: fix python3.6 issue with capture_output=True
The argument 'capture_output' is introduced in python 3.7.
In python 3.6 (on oracle linux 8), it returns an error like below
```
>>> cmd = ['ip', 'netns', 'ls']
>>> import subprocess
>>> subprocess.run(cmd, capture_output=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
```

therefore replace with stdout/stderr
```
>>> r=subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
>>> r.returncode
0
```